name: Deploy static content to Pages

on:
  push:
    branches: ["develop"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      directoriesToUpload: "./tests,./dist,./src,./themes.json"
      
    steps:
      - uses: actions/checkout@v3

      - name: Set artifact paths
        shell: bash
        run: |
          echo "Formatting artifact upload paths"
          {
            echo 'ARTIFACT_PATHS<<EOF'
            echo "${{ env.directoriesToUpload }}" | sed 's/,/\n/g'
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            ${{ env.ARTIFACT_PATHS }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
